name: "squad"
backend: "python"
max_batch_size: 512

input [
  {
    name:"input_ids"
    data_type: TYPE_UINT32
    dims: [384]
  }
]

input [
  {
    name:"segment_ids"
    data_type: TYPE_UINT32
    dims: [1]
  }
]

input [
  {
    name:"query_ids"
    data_type: TYPE_UINT64
    dims: [1]
  }
]

output [
  {
    name:"query_ids_result"
    data_type: TYPE_UINT64
    dims: [1]
  }
]

output [
  {
    name:"logits"
    data_type: TYPE_FP32
    dims: [768]
  }
]


instance_group [{
   count: 4
   kind: KIND_CPU
}]
